version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
      - galaxyofdrones-mysql:/var/lib/mysql
    networks:
      - galaxyofdrones
  redis:
    image: redis:alpine
    volumes:
      - galaxyofdrones-redis:/data
    networks:
      - galaxyofdrones
  websocket:
    image: oanhnn/laravel-echo-server
    depends_on:
      - redis
    volumes:
      - ./config/laravel-echo-server.json:/app/laravel-echo-server.json
    networks:
      - galaxyofdrones
  app:
    build: .
    image: galaxyofdrones/docker
    ports:
      - 8000:8000
    environment:
      DB_HOST: mysql
      REDIS_HOST: redis
    depends_on:
      - mysql
      - redis
      - websocket
    volumes:
      - galaxyofdrones-storage:/var/www/html/storage
      - galaxyofdrones-tile:/var/www/html/public/tile
    networks:
      - galaxyofdrones

volumes:
  galaxyofdrones-mysql:
  galaxyofdrones-redis:
  galaxyofdrones-storage:
  galaxyofdrones-tile:

networks:
  galaxyofdrones:
